# Generated by Django 5.0.2 on 2024-03-04 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hexgrid', '0001_create_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hexgrid.hexcell')),
            ],
        ),
    ]
