# Generated by Django 5.0.2 on 2024-03-03 21:16

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HexCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField()),
                ('r', models.IntegerField()),
                ('s', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='hexcell',
            constraint=models.CheckConstraint(check=models.Q(('s', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('q'), '*', models.Value(-1)), '-', models.F('r')))), name='coord_invariant'),
        ),
        migrations.AddConstraint(
            model_name='hexcell',
            constraint=models.UniqueConstraint(fields=('q', 'r', 's'), name='unique_coords'),
        ),
    ]
